name: Greeting Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Print GitHub Context
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Context: ${{ toJSON(github) }}"
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: lob/action_sam_jackson@0.0.2
        with:
          message: 'We did it!'
          token: ${{secrets.GITHUB_TOKEN}}
