name: Greeting Test

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: lob/action_sam_jackson@0.0.2
        with:
          message: 'We did it!'
          token: ${{secrets.GITHUB_TOKEN}}
