name: "Scheduler Task"

on:
  schedule:
    - cron : '*/2 * * * *'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
     - name: "Show current time"
       run: echo "The current server time is $(date +'%Y-%m-%d %H:%M:%S')"
